title: AppCraft
email: info@appcraft.hu
description: >
  AppCraft end to end. Minden, ami alkalmazásfejlesztés.
url: "http://appcraft.hu"

# Where things are
source:          .
destination:     _site
collections_dir: .
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes
debug: false
keywords: ["programozás", "web", "tanácsadás", "hirek", "Kotlin", "Java", "fejlesztés"]
algolia:
  application_id: '142FY0Z6K2'
  index_name: appcraft-site
  search_only_api_key: c2711810206b49f41be205da6dc1c80d
collections:
  blog:
    output: true
    permalink: "posts/:collection/:year/:month/:day/:title:output_ext"
    category: "posts"
    subcategory: "blog"
    display: "Blog"
  news:
    output: true
    permalink: "posts/:collection/:year/:month/:day/:title:output_ext"
    category: "posts"
    subcategory: "news"
    display: "News"
  meetups:
    output: true
    permalink: "posts/:collection/:year/:month/:day/:title:output_ext"
    category: "events"
    subcategory: "meetups"
    display: "Meetups"
  conferences:
    output: true
    permalink: "posts/:collection/:year/:month/:day/:title:output_ext"
    category: "events"
    subcategory: "conferences"
    display: "Conferences"
  workshops:
    output: true
    permalink: "posts/:collection/:year/:month/:day/:title:output_ext"
    category: "events"
    subcategory: "workshops"
    display: "Workshops"
  tags:
    output: true
    permalink: "/tags/:name/"
    category: "tags"
  authors:
    output: true
    permalink: "/authors/:name/"
    category: "authors"


# Handling Reading
safe:                 false
include:              [".htaccess"]
exclude:              ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter:  false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
plugins:
  - jekyll-gist
  - jekyll-feed

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: true

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: ""
show_dir_listing: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null
quiet:    false
verbose:  false
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "AppCraft"

# These are the default settings for each collection defined above in collections.
#
# We need to redefine category and subcategory here because these variables will be
# loaded for each path which fits a collection. The category / subcategory defined
# in the categories above is not visible sadly from the `page` variable.
# Related Jekyll issue: https://github.com/jekyll/jekyll/issues/3044
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "blog_details"
      regenerate: true
      taggable: true
      category: "posts"
      subcategory: "blog"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news_details"
      regenerate: true
      taggable: true
      category: "posts"
      subcategory: "news"
  - scope:
      path: ""
      type: "meetups"
    values:
      layout: "meetup_details"
      regenerate: true
      taggable: true
      category: "events"
      subcategory: "meetups"
  - scope:
      path: ""
      type: "conferences"
    values:
      layout: "conference_details"
      regenerate: true
      taggable: true
      category: "events"
      subcategory: "conferences"
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop_details"
      regenerate: true
      taggable: true
      category: "events"
      subcategory: "workshops"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag_details"
      regenerate: true
      category: "tags"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author_details"
      regenerate: true
      category: "authors"
liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false
