baseURL: 'https://appcraft-projects.github.io/appcraft-site/'
languageCode: en-us
title: AppCraft
googleAnalytics: ''
publishDir: docs
params:
  author: Adam Arold
  description: End to end
  githubUsername: AppCraft-Projects
  accent: teal
  showBorder: true
  backgroundColor: white
  font: Raleway
  highlight: true
  highlightStyle: solarized-dark
  highlightLanguages:
    - go
    - haskell
    - kotlin
    - scala
    - swift
menu:
  main:
    - url: /
      identifier: logo
      name: ""
      weight: 1
    - url: /programs
      identifier: programs
      name: Programs
      weight: 2
  icon:
    - url: 'mailto:info@appcraft.hu'
      name: AppCraft
      weight: 1
    - url: 'https://github.com/AppCraft-Projects/'
      name: github
      weight: 2
    - url: 'https://twitter.com/username/'
      name: twitter
      weight: 3
taxonomies:
  tag: "tags"
  category: "categories"
  event: "events"
