baseURL: 'https://appcraft-projects.github.io/appcraft-site/'
languageCode: en-us
title: AppCraft
googleAnalytics: ''
publishDir: docs
menu:
  main:
    - url: /
      identifier: home
      name: ""
      weight: 1
    - url: /programs
      identifier: programs
      name: Programs
      weight: 2
  icon:
    - url: 'mailto:info@appcraft.hu'
      name: AppCraft
      weight: 1
    - url: 'https://github.com/AppCraft-Projects/'
      name: github
      weight: 2
    - url: 'https://twitter.com/username/'
      name: twitter
      weight: 3
taxonomies:
  tag: "tags"
  category: "categories"
  event: "events"
