baseURL: 'http://appcraft.hu/'
publishDir: docs
languageCode: en-us
title: AppCraft
theme: appcraft-site-hugo-theme
disqusShortname: username
googleAnalytics: ''
params:
  author: Adam Arold
  description: End to end
  githubUsername: AppCraft-Projects
  accent: teal
  showBorder: true
  backgroundColor: white
  font: Raleway
  highlight: true
  highlightStyle: solarized-dark
  highlightLanguages:
    - go
    - haskell
    - kotlin
    - scala
    - swift
menu:
  main:
    - url: /
      name: Home
      weight: 1
    - url: /post/
      name: Posts
      weight: 2
    - url: /project/
      name: Projects
      weight: 3
  icon:
    - url: 'mailto:info@appcraft.hu'
      name: AppCraft
      weight: 1
    - url: 'https://github.com/AppCraft-Projects/'
      name: github
      weight: 2
    - url: 'https://twitter.com/username/'
      name: twitter
      weight: 3
